/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as PaverkansmatrisenRouteImport } from './routes/paverkansmatrisen'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as EkosystemRouteImport } from './routes/ekosystem'
import { Route as BrandPositionRouteImport } from './routes/brand-position'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PaverkansmatrisenRoute = PaverkansmatrisenRouteImport.update({
  id: '/paverkansmatrisen',
  path: '/paverkansmatrisen',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const EkosystemRoute = EkosystemRouteImport.update({
  id: '/ekosystem',
  path: '/ekosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandPositionRoute = BrandPositionRouteImport.update({
  id: '/brand-position',
  path: '/brand-position',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-position': typeof BrandPositionRoute
  '/ekosystem': typeof EkosystemRoute
  '/landing': typeof LandingRoute
  '/paverkansmatrisen': typeof PaverkansmatrisenRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-position': typeof BrandPositionRoute
  '/ekosystem': typeof EkosystemRoute
  '/landing': typeof LandingRoute
  '/paverkansmatrisen': typeof PaverkansmatrisenRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-position': typeof BrandPositionRoute
  '/ekosystem': typeof EkosystemRoute
  '/landing': typeof LandingRoute
  '/paverkansmatrisen': typeof PaverkansmatrisenRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-position'
    | '/ekosystem'
    | '/landing'
    | '/paverkansmatrisen'
    | '/workspace'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-position'
    | '/ekosystem'
    | '/landing'
    | '/paverkansmatrisen'
    | '/workspace'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/brand-position'
    | '/ekosystem'
    | '/landing'
    | '/paverkansmatrisen'
    | '/workspace'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandPositionRoute: typeof BrandPositionRoute
  EkosystemRoute: typeof EkosystemRoute
  LandingRoute: typeof LandingRoute
  PaverkansmatrisenRoute: typeof PaverkansmatrisenRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paverkansmatrisen': {
      id: '/paverkansmatrisen'
      path: '/paverkansmatrisen'
      fullPath: '/paverkansmatrisen'
      preLoaderRoute: typeof PaverkansmatrisenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekosystem': {
      id: '/ekosystem'
      path: '/ekosystem'
      fullPath: '/ekosystem'
      preLoaderRoute: typeof EkosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-position': {
      id: '/brand-position'
      path: '/brand-position'
      fullPath: '/brand-position'
      preLoaderRoute: typeof BrandPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandPositionRoute: BrandPositionRoute,
  EkosystemRoute: EkosystemRoute,
  LandingRoute: LandingRoute,
  PaverkansmatrisenRoute: PaverkansmatrisenRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
